# Generated by Django 2.2.2 on 2021-03-28 19:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('image', models.ImageField(blank=True, default='logoarnoldo.png', null=True, upload_to='Season/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episodies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Número de capitulo')),
                ('description', models.TextField(blank=True, null=True)),
                ('link1', models.URLField(blank=True, max_length=150, null=True, verbose_name='Link 1')),
                ('link2', models.URLField(blank=True, max_length=150, null=True, verbose_name='Link 2')),
                ('english', models.URLField(blank=True, max_length=150, null=True, verbose_name='English')),
                ('spoty', models.URLField(blank=True, max_length=150, null=True, verbose_name='Spotify')),
                ('image', models.ImageField(blank=True, default='logoarnoldo.png', null=True, upload_to='Episodie/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caps.Season')),
            ],
        ),
    ]
