# Generated by Django 2.2.2 on 2021-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodies',
            name='english',
            field=models.URLField(blank=True, max_length=1300, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='episodies',
            name='link1',
            field=models.URLField(blank=True, max_length=1300, null=True, verbose_name='Link 1'),
        ),
        migrations.AlterField(
            model_name='episodies',
            name='link2',
            field=models.URLField(blank=True, max_length=1300, null=True, verbose_name='Link 2'),
        ),
        migrations.AlterField(
            model_name='episodies',
            name='spoty',
            field=models.URLField(blank=True, max_length=1300, null=True, verbose_name='Spotify'),
        ),
    ]
