# Generated by Django 2.2.2 on 2021-03-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodies',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caps.Season'),
        ),
    ]
