# Generated by Django 2.2.2 on 2021-03-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_auto_20210326_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodies',
            name='number',
        ),
        migrations.AlterField(
            model_name='episodies',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de capitulo'),
        ),
    ]
