# Generated by Django 2.2.2 on 2021-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_auto_20210329_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodies',
            name='mediafire',
            field=models.URLField(blank=True, max_length=1300, null=True, verbose_name='Mediafire'),
        ),
    ]
