# Generated by Django 2.2.2 on 2021-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0003_episodies_mediafire'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Season/'),
        ),
    ]
