# Generated by Django 2.2.2 on 2021-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0004_season_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='ordering',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Número de capitulo'),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
