# Generated by Django 2.2.2 on 2021-04-04 04:56

import ckeditor.fields
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('caps', '0005_auto_20210331_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodies',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='episodies',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
