# Generated by Django 2.2.2 on 2021-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0005_auto_20210327_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodies',
            name='image',
            field=models.ImageField(blank=True, default='default/logoarnoldo.png', null=True, upload_to='Episodie/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(blank=True, default='default/logoarnoldo.png', null=True, upload_to='Season/'),
        ),
    ]
