# Generated by Django 2.2.2 on 2021-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
